In [1]:
# 导入绘图库
import matplotlib.pyplot as plt
# 设置绘图风格
plt.style.use('seaborn-whitegrid')
# 设置默认绘图参数 语法：plt.rc('figure', autolayout=True)用于设置figure的自动布局
#.rc()的意思是runtime configuration，用于设置matplotlib的默认参数
plt.rc('figure', autolayout=True)
plt.rc('axes', labelweight='bold', labelsize='large',
       titleweight='bold', titlesize=18, titlepad=10)

C:\Users\mingz\AppData\Local\Temp\ipykernel_49212\3461872167.py:4: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-whitegrid')

In [2]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()

# 创建数据集
os.makedirs('data', exist_ok=True)#创建一个名为data的文件夹，如果已经存在，则不创建

# 下载数据集
dataset_name = "uciml/red-wine-quality-cortez-et-al-2009"
api.dataset_download_files(dataset_name, path='data', unzip=True)#下载数据集，并解压

Dataset URL: https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009

In [3]:
import pandas as pd

red_wine = pd.read_csv('data/winequality-red.csv')
red_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
red_wine.shape #查看数据集的(行数, 列数)

(1599, 12)

In [5]:
red_wine.describe() #查看数据集的统计信息，包括均值、标准差、最小值、最大值、四分位数等

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [6]:
red_wine.info() #查看数据集的类型信息,包括数据类型、非空值数量、内存使用情况等

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [7]:
red_wine.isna().sum() #查看数据集的缺失值数量
#语法解析：.isna()用于判断数据集中的缺失值，返回一个布尔值的DataFrame，True表示缺失值，False表示非缺失值。.sum()用于计算布尔值的DataFrame中True的数量，即缺失值的数量。

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [8]:
input_shape = [11]
output_shape = [1]

from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(1, input_shape=input_shape)
])

model.summary() #查看模型结构,包括层数、每层的参数数量、总参数数量等

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 1)                 12

=================================================================
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________

In [9]:
model.weights #查看模型权重

[<tf.Variable 'dense/kernel:0' shape=(11, 1) dtype=float32, numpy=
 array([[ 0.23562872],
        [-0.4682933 ],
        [-0.6973972 ],
        [-0.1770429 ],
        [ 0.70445544],
        [ 0.01060164],
        [ 0.6080819 ],
        [ 0.37554067],
        [-0.4061707 ],
        [-0.07118165],
        [-0.63343257]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [10]:
# 转换为 numpy 数组查看具体值
for w in model.weights:
    print(f"名称: {w.name}")
    print(f"形状: {w.shape}")
    print("数值:")
    print(w.numpy())
    print("\n")

名称: dense/kernel:0
形状: (11, 1)
数值:
[[ 0.23562872]
 [-0.4682933 ]
 [-0.6973972 ]
 [-0.1770429 ]
 [ 0.70445544]
 [ 0.01060164]
 [ 0.6080819 ]
 [ 0.37554067]
 [-0.4061707 ]
 [-0.07118165]
 [-0.63343257]]


名称: dense/bias:0
形状: (1,)
数值:
[0.]